name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      # Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Instala dependencias
      - name: Install dependencies
        run: npm install

      # Build Vite
      - name: Build app
        run: npm run build

      # Instalar AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y

      # Verificar AWS CLI
      - name: Verify AWS CLI
        run: aws --version

      # Configurar AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Deploy
      - name: Deploy to S3
        run: aws s3 sync dist/ s3://bolivia-travel-christian-coronel-2026  --delete